name: ci

on:
  # Run the job when pull request closed
  # This job will only run if the PR has been merged.
  # This is commented for now to trigger the job manually only
  # pull_request:
  #   types: [ closed ]

  # This section is to trigger the workflow manually
  workflow_dispatch:

jobs:
  # Build job builds the installer go module which generates and exports go binary
  build:
    runs-on: ubuntu-latest
    #   # This job will only run if the PR has been merged.
    #   # This is commented for now to trigger the job manually only
    #   # if: github.event.pull_request.merged == true
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          registry: docker.io
          image: sureshappana/book-store-backend
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Print the list of docker images
        run: docker images
